stages:
  - containerization
  - deployment

variables:
  APPLICATION_NAME: nenkyuu-calendar

containerization:
  stage: containerization
  script:
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
    - docker build -t ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME} .
    - docker push ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}

deployment:
  stage: deployment
  script:
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE}
