stages:
  - containerization
  - deployment

variables:
  APPLICATION_NAME: nenkyuu-calendar
  KUBERNETES_PORT: 30514

  # CONTAINER_REGISTRY is provided by GitLab
  CONTAINER_IMAGE: ${CONTAINER_REGISTRY}/${APPLICATION_NAME}

containerization:
  stage: containerization
  tags:
    - moreillon
  script:
    # Building the container image
    - docker build -t ${CONTAINER_IMAGE} .
    # Push the container image to the container registry
    - docker push ${CONTAINER_IMAGE}

deployment:
  stage: deployment
  tags:
    - moreillon
  script:
    # create/update the deployment
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
    # Pull latest image of deployment
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: production
    kubernetes:
      # NAMESPACE provided by GitLab
      namespace: ${KUBERNETES_NAMESPACE}
