apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
        - name: ${APPLICATION_NAME}
          image: ${CONTAINER_IMAGE_TAGGED}
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: environment-variables
          env:
            - name: IDENTIFICATION_URL
              value: http://employee-manager/v3/users/self
---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  ports:
    - port: 80
      nodePort: ${K8S_SERVICE_PORT}
  selector:
    app: ${APPLICATION_NAME}
  type: NodePort
